
package co.aluraHotel.view;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JScrollBar;
import co.aluraHotel.Util.PageSwitch;
import co.aluraHotel.Util.Validations;
import otsViews.ScaleImg;
import otsViews.ScrollbarCustom;

/**
 *
 * @author JC
 */
public class PageSearch extends javax.swing.JFrame {

    /**
     * Creates new form PageSearch
     */
    
    ScrollbarCustom sbv = new ScrollbarCustom();
    ScrollbarCustom sbh = new ScrollbarCustom();
        
    ScaleImg scaleImg = new ScaleImg();       
    
    private PageSwitch pageSwitch;
    private Validations validations;   
    
    public PageSearch() {
        
        this.validations = new Validations();
        this.pageSwitch = new PageSwitch();
                
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
               
        scaleImg.insertImageBtnClose("/otsImages/icon-close.png", jLabelClose);
        scaleImg.insertImageBtnMin("/otsImages/icon-minimize.png", jLabelMinimize);
        
        jLabelClose.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabelMinimize.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        sbv.setForeground(new Color(151,157,233));
        jScrollPaneSearch.setVerticalScrollBar(sbv);
        
        sbh.setOrientation(JScrollBar.HORIZONTAL);
        sbh.setForeground(new Color(158,241,147));
        jScrollPaneSearch.setHorizontalScrollBar(sbh);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBG = new otsViews.PanelRoundBorderGradientColor();
        jScrollPaneSearch = new javax.swing.JScrollPane();
        jTableCompound = new javax.swing.JTable();
        jPanelButtons = new javax.swing.JPanel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        buttonSearchById = new otsViews.ButtonCustom();
        buttonSearchByName = new otsViews.ButtonCustom();
        jTextFieldFilter = new javax.swing.JTextField();
        buttonBack = new otsViews.ButtonCustom();
        jLabelFilter = new javax.swing.JLabel();
        buttonShowCompById = new otsViews.ButtonCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBG.setColor1(new java.awt.Color(74, 74, 96));
        panelBG.setColor2(new java.awt.Color(84, 97, 116));

        jScrollPaneSearch.setPreferredSize(new java.awt.Dimension(700, 200));

        jTableCompound.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Surname", "Booking ID", "Num. Guests", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCompound.setPreferredSize(new java.awt.Dimension(700, 200));
        jScrollPaneSearch.setViewportView(jTableCompound);

        jPanelButtons.setOpaque(false);
        jPanelButtons.setPreferredSize(new java.awt.Dimension(200, 90));

        jLabelMinimize.setToolTipText("Minimize");
        jLabelMinimize.setPreferredSize(new java.awt.Dimension(65, 65));
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseReleased(evt);
            }
        });

        jLabelClose.setToolTipText("Close");
        jLabelClose.setPreferredSize(new java.awt.Dimension(65, 65));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelCloseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addComponent(jLabelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMinimize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        buttonSearchById.setForeground(new java.awt.Color(60, 60, 60));
        buttonSearchById.setText("Booking ID");
        buttonSearchById.setToolTipText("Search by Booking Id and Edit");
        buttonSearchById.setColor(new java.awt.Color(255, 255, 204));
        buttonSearchById.setColorBorder(new java.awt.Color(255, 255, 204));
        buttonSearchById.setColorClick(new java.awt.Color(255, 244, 203));
        buttonSearchById.setColorOver(new java.awt.Color(35, 35, 35));
        buttonSearchById.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        buttonSearchById.setPreferredSize(new java.awt.Dimension(130, 40));
        buttonSearchById.setRadius(25);
        buttonSearchById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchByIdActionPerformed(evt);
            }
        });

        buttonSearchByName.setForeground(new java.awt.Color(60, 60, 60));
        buttonSearchByName.setText("Guest Name");
        buttonSearchByName.setToolTipText("Search by Name and Edit");
        buttonSearchByName.setColor(new java.awt.Color(255, 255, 204));
        buttonSearchByName.setColorBorder(new java.awt.Color(255, 255, 204));
        buttonSearchByName.setColorClick(new java.awt.Color(255, 244, 203));
        buttonSearchByName.setColorOver(new java.awt.Color(35, 35, 35));
        buttonSearchByName.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        buttonSearchByName.setPreferredSize(new java.awt.Dimension(130, 40));
        buttonSearchByName.setRadius(25);
        buttonSearchByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchByNameActionPerformed(evt);
            }
        });

        jTextFieldFilter.setPreferredSize(new java.awt.Dimension(200, 40));

        buttonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otsImages/icon-back.png"))); // NOI18N
        buttonBack.setToolTipText("Back");
        buttonBack.setColor(new java.awt.Color(74, 78, 83));
        buttonBack.setColorBorder(new java.awt.Color(153, 204, 255));
        buttonBack.setColorClick(new java.awt.Color(204, 212, 231));
        buttonBack.setColorOver(new java.awt.Color(58, 63, 68));
        buttonBack.setPreferredSize(new java.awt.Dimension(65, 65));
        buttonBack.setRadius(25);
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        jLabelFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otsImages/icon-search.png"))); // NOI18N
        jLabelFilter.setPreferredSize(new java.awt.Dimension(56, 56));

        buttonShowCompById.setBackground(new java.awt.Color(255, 255, 204));
        buttonShowCompById.setForeground(new java.awt.Color(60, 60, 60));
        buttonShowCompById.setText("Show Guest");
        buttonShowCompById.setToolTipText("Show Guest by Booking Id");
        buttonShowCompById.setColor(new java.awt.Color(255, 255, 204));
        buttonShowCompById.setColorBorder(new java.awt.Color(255, 255, 204));
        buttonShowCompById.setColorClick(new java.awt.Color(255, 244, 203));
        buttonShowCompById.setColorOver(new java.awt.Color(35, 35, 35));
        buttonShowCompById.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        buttonShowCompById.setPreferredSize(new java.awt.Dimension(130, 40));
        buttonShowCompById.setRadius(25);
        buttonShowCompById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowCompByIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBGLayout = new javax.swing.GroupLayout(panelBG);
        panelBG.setLayout(panelBGLayout);
        panelBGLayout.setHorizontalGroup(
            panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBGLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBGLayout.createSequentialGroup()
                        .addComponent(buttonShowCompById, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBGLayout.createSequentialGroup()
                        .addComponent(jScrollPaneSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(buttonSearchByName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonSearchById, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        panelBGLayout.setVerticalGroup(
            panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBGLayout.createSequentialGroup()
                .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBGLayout.createSequentialGroup()
                        .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(panelBGLayout.createSequentialGroup()
                        .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buttonShowCompById, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBGLayout.createSequentialGroup()
                        .addComponent(buttonSearchById, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSearchByName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        pageSwitch.searchBackMenu(this);
    }//GEN-LAST:event_buttonBackActionPerformed

    private void jLabelCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseReleased
        scaleImg.scaleImageBtnCloseEnlarge("/otsImages/icon-close.png", jLabelClose);
    }//GEN-LAST:event_jLabelCloseMouseReleased

    private void jLabelCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMousePressed
        scaleImg.scaleImageBtnCloseReduce("/otsImages/icon-close.png", jLabelClose);
    }//GEN-LAST:event_jLabelCloseMousePressed

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited
        scaleImg.insertImageBtnClose("/otsImages/icon-close.png", jLabelClose);
    }//GEN-LAST:event_jLabelCloseMouseExited

    private void jLabelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseEntered
        scaleImg.scaleImageBtnCloseEnlarge("/otsImages/icon-close.png", jLabelClose);
    }//GEN-LAST:event_jLabelCloseMouseEntered

    // -------------------------------------------------------------------------
    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        //System.exit(0);
        validations.exitValidation();
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseReleased
        scaleImg.scaleImageBtnMinEnlarge("/otsImages/icon-minimize.png", jLabelMinimize);
    }//GEN-LAST:event_jLabelMinimizeMouseReleased

    private void jLabelMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMousePressed
        scaleImg.scaleImageBtnMinReduce("/otsImages/icon-minimize.png", jLabelMinimize);
    }//GEN-LAST:event_jLabelMinimizeMousePressed

    private void jLabelMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseExited
        scaleImg.insertImageBtnMin("/otsImages/icon-minimize.png", jLabelMinimize);
    }//GEN-LAST:event_jLabelMinimizeMouseExited

    private void jLabelMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseEntered
        scaleImg.scaleImageBtnMinEnlarge("/otsImages/icon-minimize.png", jLabelMinimize);
    }//GEN-LAST:event_jLabelMinimizeMouseEntered

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    //--------------------------------------------------------------------------
    private void buttonSearchByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchByNameActionPerformed
        pageSwitch.searchForwardByName(this);
    }//GEN-LAST:event_buttonSearchByNameActionPerformed

    private void buttonSearchByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchByIdActionPerformed
        pageSwitch.searchForwardById(this);
    }//GEN-LAST:event_buttonSearchByIdActionPerformed

    private void buttonShowCompByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowCompByIdActionPerformed
        validations.tableSearchCompoundValidation(jTextFieldFilter, jTableCompound);
    }//GEN-LAST:event_buttonShowCompByIdActionPerformed
    // -------------------------------------------------------------------------
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private otsViews.ButtonCustom buttonBack;
    private otsViews.ButtonCustom buttonSearchById;
    private otsViews.ButtonCustom buttonSearchByName;
    private otsViews.ButtonCustom buttonShowCompById;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelFilter;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JScrollPane jScrollPaneSearch;
    private javax.swing.JTable jTableCompound;
    private javax.swing.JTextField jTextFieldFilter;
    private otsViews.PanelRoundBorderGradientColor panelBG;
    // End of variables declaration//GEN-END:variables
}
