
package co.aluraHotel.view;

import co.aluraHotel.Util.ClearFields;
import java.awt.Cursor;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.SpinnerNumberModel;
import co.aluraHotel.Util.PageSwitch;
import co.aluraHotel.Util.Validations;
import otsViews.SampleCalendarDesign;
import otsViews.ScaleImg;

/**
 *
 * @author JC
 */
public class PageBooking extends javax.swing.JFrame {

    /**
     * Creates new form PageBooking
     */
    
    SpinnerNumberModel spinner = new SpinnerNumberModel();
    SampleCalendarDesign scd = new SampleCalendarDesign();
    ScaleImg scaleImg = new ScaleImg();
    ClearFields clearFields = new ClearFields();
    
    private PageSwitch pageSwitch;
    private Validations validations;
    
    public PageBooking() {
        this.pageSwitch = new PageSwitch();
        this.validations = new Validations();
        
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        
        spinner.setValue(1);
        spinner.setMaximum(10);
        spinner.setMinimum(1);
        spinner.setStepSize(1);
        jSpinnerQnty.setModel(spinner);
        ((DefaultEditor) jSpinnerQnty.getEditor()).getTextField().setEditable(false);
                
        scaleImg.scaleImageBg("/otsImages/img-hotel_alura_3.png", jLabelImg);
        
        scaleImg.insertImageBtnClose("/otsImages/icon-close.png", jLabelClose);
        scaleImg.insertImageBtnMin("/otsImages/icon-minimize.png", jLabelMinimize);
        
        jLabelClose.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabelMinimize.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        comboBoxPayment.addItem("Cash");
        comboBoxPayment.addItem("Credit Card");
        comboBoxPayment.addItem("Debit Card");
        comboBoxPayment.addItem("Bank e-Transfer");
        comboBoxPayment.setSelectedIndex(-1);
        
        //
        jTextFieldPrice.setEditable(false);
        datePickerCheckin.getSettings().setAllowKeyboardEditing(false);
        datePickerCheckout.getSettings().setAllowKeyboardEditing(false);
        scd.designHighlightPolicy(datePickerCheckin);
        scd.designHighlightPolicy(datePickerCheckout);
    }

    //--------------------------------------------------------------------------
    /*public void saveDataBkW(){
        String checkin = datePickerCheckin.getDate().toString();
        String checkout = datePickerCheckout.getDate().format(DateTimeFormatter.ISO_LOCAL_DATE);
        /*System.out.println("checkin: " + checkin);
        System.out.println("checkin: " + checkin.getClass());
        System.out.println("checkin2: " + checkout);
        System.out.println("checkin2: " + checkout.getClass());*/
        /*Booking booking = new Booking(java.sql.Date.valueOf(checkin),
                                      java.sql.Date.valueOf(checkout),
                                      (Integer)jSpinnerQnty.getValue(),
                                      Double.parseDouble(jTextFieldPrice.getText()),
                                      (String)comboBoxPayment.getSelectedItem());
        bookingController.saveBk(booking);
    }*/
    //--------------------------------------------------------------------------
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBG = new otsViews.PanelRoundBorderGradientColor();
        panelComp = new otsViews.PanelRoundBorderGradientColor();
        jLabelTitle = new javax.swing.JLabel();
        jLabelCheckinIcon = new javax.swing.JLabel();
        jLabelCheckoutIcon = new javax.swing.JLabel();
        jLabelPriceIcon = new javax.swing.JLabel();
        jLabelPaymentIcon = new javax.swing.JLabel();
        jLabelCheckin = new javax.swing.JLabel();
        jLabelCheckout = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabelPayment = new javax.swing.JLabel();
        datePickerCheckin = new com.github.lgooddatepicker.components.DatePicker();
        jTextFieldPrice = new javax.swing.JTextField();
        datePickerCheckout = new com.github.lgooddatepicker.components.DatePicker();
        jLabelQuantity = new javax.swing.JLabel();
        jLabelQnty = new javax.swing.JLabel();
        jSpinnerQnty = new javax.swing.JSpinner();
        comboBoxPayment = new otsViews.ComboBoxCustom();
        jPanelButtons = new javax.swing.JPanel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelImg = new javax.swing.JLabel();
        buttonCancelAndBack = new otsViews.ButtonCustom();
        buttonAcceptAndContinue = new otsViews.ButtonCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBG.setColor1(new java.awt.Color(74, 74, 96));
        panelBG.setColor2(new java.awt.Color(84, 97, 116));
        panelBG.setPreferredSize(new java.awt.Dimension(900, 500));

        panelComp.setColor1(new java.awt.Color(74, 74, 96));
        panelComp.setColor2(new java.awt.Color(84, 97, 116));
        panelComp.setRoundBottomLeft(50);
        panelComp.setRoundBottomRight(50);
        panelComp.setRoundTopLeft(50);
        panelComp.setRoundTopRight(50);

        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Booking System");
        jLabelTitle.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(204, 204, 204));

        jLabelCheckinIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otsImages/icon-calendar.png"))); // NOI18N
        jLabelCheckinIcon.setPreferredSize(new java.awt.Dimension(56, 56));

        jLabelCheckoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otsImages/icon-calendar.png"))); // NOI18N
        jLabelCheckoutIcon.setPreferredSize(new java.awt.Dimension(56, 56));

        jLabelPriceIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otsImages/icon-price.png"))); // NOI18N
        jLabelPriceIcon.setPreferredSize(new java.awt.Dimension(56, 56));

        jLabelPaymentIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otsImages/icon-payment_method.png"))); // NOI18N
        jLabelPaymentIcon.setPreferredSize(new java.awt.Dimension(56, 56));

        jLabelCheckin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCheckin.setText("Check In");
        jLabelCheckin.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabelCheckin.setForeground(new java.awt.Color(204, 216, 233));
        jLabelCheckin.setPreferredSize(new java.awt.Dimension(120, 25));

        jLabelCheckout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCheckout.setText("Check Out");
        jLabelCheckout.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabelCheckout.setForeground(new java.awt.Color(204, 216, 233));
        jLabelCheckout.setPreferredSize(new java.awt.Dimension(120, 25));

        jLabelPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrice.setText("Price");
        jLabelPrice.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabelPrice.setForeground(new java.awt.Color(204, 216, 233));
        jLabelPrice.setPreferredSize(new java.awt.Dimension(120, 25));

        jLabelPayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPayment.setText("Payment method");
        jLabelPayment.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabelPayment.setForeground(new java.awt.Color(204, 216, 233));
        jLabelPayment.setPreferredSize(new java.awt.Dimension(125, 25));

        datePickerCheckin.setOpaque(false);

        jTextFieldPrice.setEditable(false);
        jTextFieldPrice.setBackground(new java.awt.Color(84, 97, 116));
        jTextFieldPrice.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldPrice.setPreferredSize(new java.awt.Dimension(181, 29));

        datePickerCheckout.setOpaque(false);

        jLabelQuantity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otsImages/icon-qnty.png"))); // NOI18N

        jLabelQnty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQnty.setText("Guests");
        jLabelQnty.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabelQnty.setForeground(new java.awt.Color(204, 216, 233));
        jLabelQnty.setPreferredSize(new java.awt.Dimension(120, 25));

        jSpinnerQnty.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSpinnerQnty.setFocusable(false);
        jSpinnerQnty.setPreferredSize(new java.awt.Dimension(100, 29));

        comboBoxPayment.setOpaque(false);
        comboBoxPayment.setPreferredSize(new java.awt.Dimension(181, 32));

        javax.swing.GroupLayout panelCompLayout = new javax.swing.GroupLayout(panelComp);
        panelComp.setLayout(panelCompLayout);
        panelCompLayout.setHorizontalGroup(
            panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCompLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitle)
                .addGap(203, 203, 203))
            .addGroup(panelCompLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCompLayout.createSequentialGroup()
                        .addComponent(jLabelQuantity)
                        .addGap(18, 18, 18)
                        .addGroup(panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelQnty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerQnty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(panelCompLayout.createSequentialGroup()
                        .addGroup(panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCompLayout.createSequentialGroup()
                                .addComponent(jLabelPriceIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelCompLayout.createSequentialGroup()
                                .addComponent(jLabelCheckinIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datePickerCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCompLayout.createSequentialGroup()
                                .addComponent(jLabelPaymentIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelCompLayout.createSequentialGroup()
                                        .addComponent(jLabelPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(83, 83, 83))
                                    .addGroup(panelCompLayout.createSequentialGroup()
                                        .addComponent(comboBoxPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(27, 27, 27))))
                            .addGroup(panelCompLayout.createSequentialGroup()
                                .addComponent(jLabelCheckoutIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datePickerCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27))))))
        );
        panelCompLayout.setVerticalGroup(
            panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCompLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabelTitle)
                .addGap(71, 71, 71)
                .addGroup(panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelCheckinIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCheckoutIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCompLayout.createSequentialGroup()
                        .addComponent(jLabelCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datePickerCheckin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCompLayout.createSequentialGroup()
                        .addComponent(jLabelCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datePickerCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCompLayout.createSequentialGroup()
                        .addComponent(jLabelQnty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerQnty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCompLayout.createSequentialGroup()
                        .addComponent(jLabelPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelPriceIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelCompLayout.createSequentialGroup()
                            .addComponent(jLabelPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabelPaymentIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
        );

        jPanelButtons.setPreferredSize(new java.awt.Dimension(200, 90));
        jPanelButtons.setOpaque(false);

        jLabelMinimize.setPreferredSize(new java.awt.Dimension(65, 65));
        jLabelMinimize.setToolTipText("Minimize");
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseReleased(evt);
            }
        });

        jLabelClose.setPreferredSize(new java.awt.Dimension(65, 65));
        jLabelClose.setToolTipText("Close");
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelCloseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addComponent(jLabelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMinimize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabelImg.setPreferredSize(new java.awt.Dimension(100, 50));

        buttonCancelAndBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otsImages/icon-cancel.png"))); // NOI18N
        buttonCancelAndBack.setText("Cancel");
        buttonCancelAndBack.setColor(new java.awt.Color(51, 51, 51));
        buttonCancelAndBack.setColorBorder(new java.awt.Color(255, 142, 124));
        buttonCancelAndBack.setColorClick(new java.awt.Color(255, 204, 204));
        buttonCancelAndBack.setColorOver(new java.awt.Color(35, 35, 35));
        buttonCancelAndBack.setForeground(new java.awt.Color(204, 204, 204));
        buttonCancelAndBack.setPreferredSize(new java.awt.Dimension(125, 45));
        buttonCancelAndBack.setRadius(25);
        buttonCancelAndBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelAndBackActionPerformed(evt);
            }
        });

        buttonAcceptAndContinue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otsImages/icon-accept.png"))); // NOI18N
        buttonAcceptAndContinue.setText("Accept");
        buttonAcceptAndContinue.setColor(new java.awt.Color(51, 51, 51));
        buttonAcceptAndContinue.setColorBorder(new java.awt.Color(153, 255, 153));
        buttonAcceptAndContinue.setColorClick(new java.awt.Color(204, 255, 204));
        buttonAcceptAndContinue.setColorOver(new java.awt.Color(35, 35, 35));
        buttonAcceptAndContinue.setForeground(new java.awt.Color(204, 204, 204));
        buttonAcceptAndContinue.setPreferredSize(new java.awt.Dimension(125, 45));
        buttonAcceptAndContinue.setRadius(25);
        buttonAcceptAndContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAcceptAndContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBGLayout = new javax.swing.GroupLayout(panelBG);
        panelBG.setLayout(panelBGLayout);
        panelBGLayout.setHorizontalGroup(
            panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBGLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBGLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBGLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBGLayout.createSequentialGroup()
                                .addComponent(buttonCancelAndBack, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonAcceptAndContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        panelBGLayout.setVerticalGroup(
            panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBGLayout.createSequentialGroup()
                .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBGLayout.createSequentialGroup()
                        .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonCancelAndBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAcceptAndContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelBGLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(panelComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void buttonAcceptAndContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAcceptAndContinueActionPerformed
        validations.bookingValidation(datePickerCheckin, datePickerCheckout, jSpinnerQnty, jTextFieldPrice, comboBoxPayment, this);
    }//GEN-LAST:event_buttonAcceptAndContinueActionPerformed

    private void buttonCancelAndBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelAndBackActionPerformed
        clearFields.clearBookingPage(datePickerCheckin, datePickerCheckout, jSpinnerQnty, jTextFieldPrice, comboBoxPayment);
        pageSwitch.bookingBackMenu(this);
    }//GEN-LAST:event_buttonCancelAndBackActionPerformed

    private void jLabelCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseReleased
        scaleImg.scaleImageBtnCloseEnlarge("/otsImages/icon-close.png", jLabelClose);
    }//GEN-LAST:event_jLabelCloseMouseReleased

    private void jLabelCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMousePressed
        scaleImg.scaleImageBtnCloseReduce("/otsImages/icon-close.png", jLabelClose);
    }//GEN-LAST:event_jLabelCloseMousePressed

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited
        scaleImg.insertImageBtnClose("/otsImages/icon-close.png", jLabelClose);
    }//GEN-LAST:event_jLabelCloseMouseExited

    private void jLabelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseEntered
        scaleImg.scaleImageBtnCloseEnlarge("/otsImages/icon-close.png", jLabelClose);
    }//GEN-LAST:event_jLabelCloseMouseEntered

    // -------------------------------------------------------------------------
    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        //System.exit(0);
        validations.exitValidation();
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseReleased
        scaleImg.scaleImageBtnMinEnlarge("/otsImages/icon-minimize.png", jLabelMinimize);
    }//GEN-LAST:event_jLabelMinimizeMouseReleased

    private void jLabelMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMousePressed
        scaleImg.scaleImageBtnMinReduce("/otsImages/icon-minimize.png", jLabelMinimize);
    }//GEN-LAST:event_jLabelMinimizeMousePressed

    private void jLabelMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseExited
        scaleImg.insertImageBtnMin("/otsImages/icon-minimize.png", jLabelMinimize);
    }//GEN-LAST:event_jLabelMinimizeMouseExited

    private void jLabelMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseEntered
        scaleImg.scaleImageBtnMinEnlarge("/otsImages/icon-minimize.png", jLabelMinimize);
    }//GEN-LAST:event_jLabelMinimizeMouseEntered

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked
    // -------------------------------------------------------------------------
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private otsViews.ButtonCustom buttonAcceptAndContinue;
    private otsViews.ButtonCustom buttonCancelAndBack;
    private otsViews.ComboBoxCustom comboBoxPayment;
    private com.github.lgooddatepicker.components.DatePicker datePickerCheckin;
    private com.github.lgooddatepicker.components.DatePicker datePickerCheckout;
    private javax.swing.JLabel jLabelCheckin;
    private javax.swing.JLabel jLabelCheckinIcon;
    private javax.swing.JLabel jLabelCheckout;
    private javax.swing.JLabel jLabelCheckoutIcon;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelPayment;
    private javax.swing.JLabel jLabelPaymentIcon;
    private javax.swing.JLabel jLabelPrice;
    private javax.swing.JLabel jLabelPriceIcon;
    private javax.swing.JLabel jLabelQnty;
    private javax.swing.JLabel jLabelQuantity;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JSpinner jSpinnerQnty;
    private javax.swing.JTextField jTextFieldPrice;
    private otsViews.PanelRoundBorderGradientColor panelBG;
    private otsViews.PanelRoundBorderGradientColor panelComp;
    // End of variables declaration//GEN-END:variables
}
