
package co.aluraHotel.view;

import co.aluraHotel.controller.BookingController;
import co.aluraHotel.controller.GuestsController;
import java.awt.Color;
import javax.swing.JScrollBar;
import co.aluraHotel.Util.PageSwitch;
import co.aluraHotel.Util.Validations;
import otsViews.ScaleImg;
import otsViews.ScrollbarCustom;

/**
 *
 * @author JC
 */
public class PageSearchById extends javax.swing.JFrame {

    /**
     * Creates new form PageSearch
     */
    
    ScrollbarCustom sbv = new ScrollbarCustom();
    ScrollbarCustom sbh = new ScrollbarCustom();
    ScaleImg scaleImg = new ScaleImg();
    
    private BookingController bookingController;
    private GuestsController guestsController;
    
    private PageSwitch pageSwitch;
    private Validations validations;
    
    public PageSearchById() {
        this.bookingController = new BookingController();
        this.guestsController = new GuestsController();
        
        this.pageSwitch = new PageSwitch();
        this.validations = new Validations();
        
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
        
        sbv.setForeground(new Color(151,157,233));
        jScrollPaneSearch.setVerticalScrollBar(sbv);
        
        sbh.setOrientation(JScrollBar.HORIZONTAL);
        sbh.setForeground(new Color(158,241,147));
        jScrollPaneSearch.setHorizontalScrollBar(sbh);
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBG = new otsViews.PanelRoundBorderGradientColor();
        jScrollPaneSearch = new javax.swing.JScrollPane();
        jTableSearchById = new javax.swing.JTable();
        buttonEdit = new otsViews.ButtonCustom();
        buttonDelete = new otsViews.ButtonCustom();
        buttonCancel = new otsViews.ButtonCustom();
        buttonAccept = new otsViews.ButtonCustom();
        buttonBack = new otsViews.ButtonCustom();
        jTextFieldFilter = new javax.swing.JTextField();
        buttonSearch = new otsViews.ButtonCustom();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBG.setColor1(new java.awt.Color(74, 74, 96));
        panelBG.setColor2(new java.awt.Color(84, 97, 116));
        panelBG.setPreferredSize(new java.awt.Dimension(900, 380));

        jScrollPaneSearch.setPreferredSize(new java.awt.Dimension(700, 200));

        jTableSearchById.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Booking ID", "Check In", "Check Out", "Num. Guests", "Price", "Payment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSearchById.setPreferredSize(new java.awt.Dimension(700, 200));
        jScrollPaneSearch.setViewportView(jTableSearchById);

        buttonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otsImages/icon-edit.png"))); // NOI18N
        buttonEdit.setColor(new java.awt.Color(74, 78, 83));
        buttonEdit.setColorBorder(new java.awt.Color(153, 204, 255));
        buttonEdit.setColorClick(new java.awt.Color(204, 212, 231));
        buttonEdit.setColorOver(new java.awt.Color(58, 63, 68));
        buttonEdit.setPreferredSize(new java.awt.Dimension(65, 65));
        buttonEdit.setRadius(25);
        buttonEdit.setToolTipText("Edit");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otsImages/icon-delete.png"))); // NOI18N
        buttonDelete.setColor(new java.awt.Color(74, 78, 83));
        buttonDelete.setColorBorder(new java.awt.Color(153, 204, 255));
        buttonDelete.setColorClick(new java.awt.Color(204, 212, 231));
        buttonDelete.setColorOver(new java.awt.Color(58, 63, 68));
        buttonDelete.setPreferredSize(new java.awt.Dimension(65, 65));
        buttonDelete.setRadius(25);
        buttonDelete.setToolTipText("Delete");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otsImages/icon-cancel_2.png"))); // NOI18N
        buttonCancel.setColor(new java.awt.Color(51, 51, 51));
        buttonCancel.setColorBorder(new java.awt.Color(255, 142, 124));
        buttonCancel.setColorClick(new java.awt.Color(255, 204, 204));
        buttonCancel.setColorOver(new java.awt.Color(35, 35, 35));
        buttonCancel.setPreferredSize(new java.awt.Dimension(65, 65));
        buttonCancel.setRadius(25);

        buttonAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otsImages/icon-accept_2.png"))); // NOI18N
        buttonAccept.setColor(new java.awt.Color(51, 51, 51));
        buttonAccept.setColorBorder(new java.awt.Color(153, 255, 153));
        buttonAccept.setColorClick(new java.awt.Color(204, 255, 204));
        buttonAccept.setColorOver(new java.awt.Color(35, 35, 35));
        buttonAccept.setPreferredSize(new java.awt.Dimension(65, 65));
        buttonAccept.setRadius(25);

        buttonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otsImages/icon-back.png"))); // NOI18N
        buttonBack.setColor(new java.awt.Color(74, 78, 83));
        buttonBack.setColorBorder(new java.awt.Color(153, 204, 255));
        buttonBack.setColorClick(new java.awt.Color(204, 212, 231));
        buttonBack.setColorOver(new java.awt.Color(58, 63, 68));
        buttonBack.setPreferredSize(new java.awt.Dimension(65, 65));
        buttonBack.setRadius(25);
        buttonBack.setToolTipText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        jTextFieldFilter.setPreferredSize(new java.awt.Dimension(200, 40));

        buttonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otsImages/icon-search.png"))); // NOI18N
        buttonSearch.setColor(new java.awt.Color(74, 78, 83));
        buttonSearch.setColorBorder(new java.awt.Color(153, 204, 255));
        buttonSearch.setColorClick(new java.awt.Color(204, 212, 231));
        buttonSearch.setColorOver(new java.awt.Color(58, 63, 68));
        buttonSearch.setPreferredSize(new java.awt.Dimension(60, 60));
        buttonSearch.setRadius(25);
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search by Id");
        jLabel1.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 40));

        javax.swing.GroupLayout panelBGLayout = new javax.swing.GroupLayout(panelBG);
        panelBG.setLayout(panelBGLayout);
        panelBGLayout.setHorizontalGroup(
            panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBGLayout.createSequentialGroup()
                .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBGLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPaneSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBGLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBGLayout.createSequentialGroup()
                            .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(buttonAccept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelBGLayout.createSequentialGroup()
                            .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelBGLayout.setVerticalGroup(
            panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBGLayout.createSequentialGroup()
                .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBGLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBGLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBGLayout.createSequentialGroup()
                        .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonAccept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        pageSwitch.searchByBack(this);
    }//GEN-LAST:event_buttonBackActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        validations.tableSearchByIdValidation(jTextFieldFilter, jTableSearchById);
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        validations.editByIdValidation(jTableSearchById);
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        validations.deleteByIdValidation(jTableSearchById);
    }//GEN-LAST:event_buttonDeleteActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageSearchById.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageSearchById.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageSearchById.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageSearchById.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageSearchById().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private otsViews.ButtonCustom buttonAccept;
    private otsViews.ButtonCustom buttonBack;
    private otsViews.ButtonCustom buttonCancel;
    private otsViews.ButtonCustom buttonDelete;
    private otsViews.ButtonCustom buttonEdit;
    private otsViews.ButtonCustom buttonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPaneSearch;
    private javax.swing.JTable jTableSearchById;
    private javax.swing.JTextField jTextFieldFilter;
    private otsViews.PanelRoundBorderGradientColor panelBG;
    // End of variables declaration//GEN-END:variables
}
