
package co.aluraHotel.view;

import java.awt.Cursor;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import co.aluraHotel.Util.PageSwitch;
import co.aluraHotel.Util.Validations;
import otsViews.ScaleImg;

/**
 *
 * @author JC
 */
public class PageMenuOptions extends javax.swing.JFrame {

    /**
     * Creates new form PageOptions
     */
    
    ScaleImg scaleImg = new ScaleImg();
    private PageSwitch pageSwitch;
    private Validations val;
    
    public PageMenuOptions() {
        this.setUndecorated(true);
        this.pageSwitch = new PageSwitch();
        this.val = new Validations();
        initComponents();
        //this.setOpacity(.9f);
        this.setLocationRelativeTo(null);
        scaleImg.scaleImageBg("/otsImages/img-hotel_alura_4.png", jLabelImgHotel);
        
        scaleImg.insertImageBtnClose("/otsImages/icon-close.png", jLabelClose);
        scaleImg.insertImageBtnMin("/otsImages/icon-minimize.png", jLabelMinimize);
        jLabelClose.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabelMinimize.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        buttonBooking.setCursor(new Cursor(Cursor.HAND_CURSOR));
        buttonSearch.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    
    // close window --------------------------------------------------------------------------
    public void closeFrame(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    } 
    // close window --------------------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFrame = new otsViews.PanelRoundBorderGradientColor();
        jLabelImgHotel = new javax.swing.JLabel();
        panelBooking = new otsViews.PanelRoundBorderGradientColor();
        jLabelBooking = new javax.swing.JLabel();
        buttonBooking = new otsViews.ButtonCustom();
        panelSearch = new otsViews.PanelRoundBorderGradientColor();
        jLabelSearch = new javax.swing.JLabel();
        buttonSearch = new otsViews.ButtonCustom();
        jPanelButtons = new javax.swing.JPanel();
        jLabelMinimize = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        buttonCustomLogOut = new otsViews.ButtonCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFrame.setColor1(new java.awt.Color(74, 74, 96));
        panelFrame.setColor2(new java.awt.Color(84, 97, 116));
        panelFrame.setPreferredSize(new java.awt.Dimension(650, 360));

        jLabelImgHotel.setPreferredSize(new java.awt.Dimension(100, 100));

        panelBooking.setColor1(new java.awt.Color(74, 78, 83));
        panelBooking.setColor2(new java.awt.Color(84, 97, 116));
        panelBooking.setPreferredSize(new java.awt.Dimension(120, 120));
        panelBooking.setRoundBottomLeft(50);
        panelBooking.setRoundTopRight(50);

        jLabelBooking.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBooking.setText("Booking");
        jLabelBooking.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabelBooking.setForeground(new java.awt.Color(204, 216, 233));

        buttonBooking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otsImages/icon-baggage.png"))); // NOI18N
        buttonBooking.setColor(new java.awt.Color(74, 78, 83));
        buttonBooking.setColorBorder(new java.awt.Color(153, 204, 255));
        buttonBooking.setColorClick(new java.awt.Color(204, 212, 231));
        buttonBooking.setColorOver(new java.awt.Color(58, 63, 68));
        buttonBooking.setPreferredSize(new java.awt.Dimension(65, 65));
        buttonBooking.setRadius(25);
        buttonBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBookingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBookingLayout = new javax.swing.GroupLayout(panelBooking);
        panelBooking.setLayout(panelBookingLayout);
        panelBookingLayout.setHorizontalGroup(
            panelBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBookingLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelBookingLayout.setVerticalGroup(
            panelBookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBookingLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(buttonBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBooking)
                .addGap(12, 12, 12))
        );

        panelSearch.setColor1(new java.awt.Color(84, 97, 116));
        panelSearch.setColor2(new java.awt.Color(74, 78, 83));
        panelSearch.setPreferredSize(new java.awt.Dimension(120, 120));
        panelSearch.setRoundBottomRight(50);
        panelSearch.setRoundTopLeft(50);

        jLabelSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSearch.setText("Search");
        jLabelSearch.setFont(new java.awt.Font("Cantarell Extra Bold", 0, 15)); // NOI18N
        jLabelSearch.setForeground(new java.awt.Color(204, 216, 233));

        buttonSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otsImages/icon-search.png"))); // NOI18N
        buttonSearch.setColor(new java.awt.Color(74, 78, 83));
        buttonSearch.setColorBorder(new java.awt.Color(153, 204, 255));
        buttonSearch.setColorClick(new java.awt.Color(204, 212, 231));
        buttonSearch.setColorOver(new java.awt.Color(58, 63, 68));
        buttonSearch.setPreferredSize(new java.awt.Dimension(65, 65));
        buttonSearch.setRadius(25);
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSearch)
                .addGap(12, 12, 12))
        );

        jPanelButtons.setPreferredSize(new java.awt.Dimension(200, 90));
        jPanelButtons.setOpaque(false);

        jLabelMinimize.setPreferredSize(new java.awt.Dimension(65, 65));
        jLabelMinimize.setRequestFocusEnabled(false);
        jLabelMinimize.setToolTipText("Minimize");
        jLabelMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelMinimizeMouseReleased(evt);
            }
        });

        jLabelClose.setPreferredSize(new java.awt.Dimension(65, 65));
        jLabelClose.setToolTipText("Close");
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelCloseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelButtonsLayout = new javax.swing.GroupLayout(jPanelButtons);
        jPanelButtons.setLayout(jPanelButtonsLayout);
        jPanelButtonsLayout.setHorizontalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addComponent(jLabelMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanelButtonsLayout.setVerticalGroup(
            jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButtonsLayout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addGroup(jPanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMinimize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        buttonCustomLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otsImages/icon-log_out.png"))); // NOI18N
        buttonCustomLogOut.setToolTipText("Log Out");
        buttonCustomLogOut.setColor(new java.awt.Color(51, 51, 51));
        buttonCustomLogOut.setColorBorder(new java.awt.Color(255, 142, 124));
        buttonCustomLogOut.setColorClick(new java.awt.Color(65, 65, 65));
        buttonCustomLogOut.setColorOver(new java.awt.Color(35, 35, 35));
        buttonCustomLogOut.setPreferredSize(new java.awt.Dimension(82, 82));
        buttonCustomLogOut.setRadius(40);
        buttonCustomLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustomLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFrameLayout = new javax.swing.GroupLayout(panelFrame);
        panelFrame.setLayout(panelFrameLayout);
        panelFrameLayout.setHorizontalGroup(
            panelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelFrameLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(panelBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabelImgHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(buttonCustomLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        panelFrameLayout.setVerticalGroup(
            panelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFrameLayout.createSequentialGroup()
                .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFrameLayout.createSequentialGroup()
                        .addGap(0, 42, Short.MAX_VALUE)
                        .addGroup(panelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelBooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108))
                    .addGroup(panelFrameLayout.createSequentialGroup()
                        .addGroup(panelFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonCustomLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelImgHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFrame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCustomLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomLogOutActionPerformed
        //pageSwitch.menuLogout(this);
        val.logoutValidation(this);
    }//GEN-LAST:event_buttonCustomLogOutActionPerformed

    private void jLabelCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseReleased
        scaleImg.scaleImageBtnCloseEnlarge("/otsImages/icon-close.png", jLabelClose);
    }//GEN-LAST:event_jLabelCloseMouseReleased

    private void jLabelCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMousePressed
        scaleImg.scaleImageBtnCloseReduce("/otsImages/icon-close.png", jLabelClose);
    }//GEN-LAST:event_jLabelCloseMousePressed

    private void jLabelCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseExited
        scaleImg.insertImageBtnClose("/otsImages/icon-close.png", jLabelClose);
    }//GEN-LAST:event_jLabelCloseMouseExited

    private void jLabelCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseEntered
        scaleImg.scaleImageBtnCloseEnlarge("/otsImages/icon-close.png", jLabelClose);
    }//GEN-LAST:event_jLabelCloseMouseEntered

    // -------------------------------------------------------------------------
    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        //System.exit(0);
        val.exitValidation();
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseReleased
        scaleImg.scaleImageBtnMinEnlarge("/otsImages/icon-minimize.png", jLabelMinimize);
    }//GEN-LAST:event_jLabelMinimizeMouseReleased

    private void jLabelMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMousePressed
        scaleImg.scaleImageBtnMinReduce("/otsImages/icon-minimize.png", jLabelMinimize);
    }//GEN-LAST:event_jLabelMinimizeMousePressed

    private void jLabelMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseExited
        scaleImg.insertImageBtnMin("/otsImages/icon-minimize.png", jLabelMinimize);
    }//GEN-LAST:event_jLabelMinimizeMouseExited

    private void jLabelMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseEntered
        scaleImg.scaleImageBtnMinEnlarge("/otsImages/icon-minimize.png", jLabelMinimize);
    }//GEN-LAST:event_jLabelMinimizeMouseEntered

    private void jLabelMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimizeMouseClicked
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabelMinimizeMouseClicked

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        pageSwitch.menuSearch(this);
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void buttonBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBookingActionPerformed
        pageSwitch.menuBooking(this);
    }//GEN-LAST:event_buttonBookingActionPerformed
        // -------------------------------------------------------------------------
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageMenuOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageMenuOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageMenuOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageMenuOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageMenuOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private otsViews.ButtonCustom buttonBooking;
    private otsViews.ButtonCustom buttonCustomLogOut;
    private otsViews.ButtonCustom buttonSearch;
    private javax.swing.JLabel jLabelBooking;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelImgHotel;
    private javax.swing.JLabel jLabelMinimize;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JPanel jPanelButtons;
    private otsViews.PanelRoundBorderGradientColor panelBooking;
    private otsViews.PanelRoundBorderGradientColor panelFrame;
    private otsViews.PanelRoundBorderGradientColor panelSearch;
    // End of variables declaration//GEN-END:variables
}
