
package co.aluraHotel.test;

import co.aluraHotel.controller.BookingController;
import co.aluraHotel.controller.GuestsController;
import java.sql.Date;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import co.aluraHotel.Util.ViewSearchMethods;

/**
 *
 * @author JC
 */
public class TestTable extends javax.swing.JFrame {

    /**
     * Creates new form TestTable
     */
    
    private ViewSearchMethods viewSearchMethods;
    private BookingController bookingController;
    private GuestsController guestsController;
        
    public TestTable() {
        initComponents();
        this.viewSearchMethods = new ViewSearchMethods(); 
        this.bookingController = new BookingController();
        this.guestsController = new GuestsController();
        
        tableModelBooking();
        tableModelGuests();
        tableModelComp();
    }
    
    //--------------------------------------------------------------------------    
    public void tableModelBooking() {
        DefaultTableModel jTableTestModel = (DefaultTableModel) jTableTest.getModel();
        jTableTestModel.addColumn("Booking Id");
        jTableTestModel.addColumn("Check In");
        jTableTestModel.addColumn("Check Out");
        jTableTestModel.addColumn("Guests Qty");
        jTableTestModel.addColumn("Price");
        jTableTestModel.addColumn("Payment Method");
        viewSearchMethods.createTableBooking(jTableTest);
    }
    
    public void tableModelGuests() {
        DefaultTableModel jTableTest1Model = (DefaultTableModel) jTableTest1.getModel();
        jTableTest1Model.addColumn("Guest Id");
        jTableTest1Model.addColumn("Name");
        jTableTest1Model.addColumn("Surname");
        jTableTest1Model.addColumn("Birth Date");
        jTableTest1Model.addColumn("Nationality");
        jTableTest1Model.addColumn("Phone");
        jTableTest1Model.addColumn("eMail");
        jTableTest1Model.addColumn("Booking Id");
        viewSearchMethods.createTableGuests(jTableTest1);
    }
    
    public void tableModelComp() {
        DefaultTableModel jTableTest2Model = (DefaultTableModel) jTableTest2.getModel();
        jTableTest2Model.addColumn("Name");
        jTableTest2Model.addColumn("Surname");
        jTableTest2Model.addColumn("Booking Id");
        jTableTest2Model.addColumn("Qty Guests");
        jTableTest2Model.addColumn("Price");
        viewSearchMethods.createTableJoin(jTableTest2);
    }
    
    //--------------------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTest = new javax.swing.JTable();
        jButtonSearchByName = new javax.swing.JButton();
        jButtonSearchById = new javax.swing.JButton();
        jTextFieldSearch = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableTest1 = new javax.swing.JTable();
        jButtonComp = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableTest2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTableTest);

        jButtonSearchByName.setText("SearchByName");
        jButtonSearchByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchByNameActionPerformed(evt);
            }
        });

        jButtonSearchById.setText("SearchById");
        jButtonSearchById.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSearchByIdMouseClicked(evt);
            }
        });
        jButtonSearchById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchByIdActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jTableTest1);

        jButtonComp.setText("CompById");
        jButtonComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(jTableTest2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSearchById)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSearchByName)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonComp)
                        .addGap(160, 160, 160)
                        .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearchByName)
                    .addComponent(jButtonSearchById)
                    .addComponent(jTextFieldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonComp))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchByIdActionPerformed
        viewSearchMethods.cleanTableVSM(jTableTest);
       
        if (jTextFieldSearch.getText().equals("")) {
            viewSearchMethods.createTableBooking(jTableTest);          
        } else {           
            viewSearchMethods.createTableBookingById(jTextFieldSearch, jTableTest);
        }    
    }//GEN-LAST:event_jButtonSearchByIdActionPerformed

    private void jButtonSearchByIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSearchByIdMouseClicked
            
    }//GEN-LAST:event_jButtonSearchByIdMouseClicked

    private void jButtonSearchByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchByNameActionPerformed
        viewSearchMethods.cleanTableVSM(jTableTest1);
        if (jTextFieldSearch.getText().equals("")) {
            viewSearchMethods.createTableGuests(jTableTest1);
        } else {
            viewSearchMethods.createTableGuestsByName(jTextFieldSearch, jTableTest1);
        }
    }//GEN-LAST:event_jButtonSearchByNameActionPerformed

    private void jButtonCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompActionPerformed
        viewSearchMethods.cleanTableVSM(jTableTest2);
        if (jTextFieldSearch.getText().equals("")) {
            viewSearchMethods.createTableJoin(jTableTest2);
        } else {
            viewSearchMethods.createTableJoinById(jTextFieldSearch, jTableTest2);
        }
        
    }//GEN-LAST:event_jButtonCompActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComp;
    private javax.swing.JButton jButtonSearchById;
    private javax.swing.JButton jButtonSearchByName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableTest;
    private javax.swing.JTable jTableTest1;
    private javax.swing.JTable jTableTest2;
    private javax.swing.JTextField jTextFieldSearch;
    // End of variables declaration//GEN-END:variables
}
